spring.application.name=desafio-tech-cadastro-agencias

logging.level.org.springframework.jdbc=DEBUG

spring.h2.console.enabled=true
spring.datasource.generate-unique-name=false
spring.datasource.name=super-bank